name: Publish Docker image to docker hub

on:
  push:
    branches:
      - master
jobs:
  semantic-release:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Semantic release
        run: npx semantic-release
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
